# Site settings
title: rialitybytes.art
subtitle: on a quest to follow my curiousity
email: youremailaddress@gmail.com
description: an online home for the words and images that float around my brain
baseurl: "/rialitybytes.art" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Ria
# street_address: 1234 Somewhere Road
city: Taipei
# state: TN
# zip_code: 55555
country: Taiwan
# phone: (716) 555-5555

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/rialitybytes.art
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
